package Main;

/**
 * Redes Integradas de Telecomunicações II
 * MIEEC 2020/2021
 *
 * httpThread.java
 *
 * Main class with graphical interface and main thread that accepts incoming connections
 * Calls httpThread to handle individual HTTP requests
 * INCOMPLETE VERSION
 *
 */

import HTTPFormat.Log;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import javax.net.ssl.*;
import java.security.*;
import java.net.UnknownHostException;


public class guiHttpd extends javax.swing.JFrame implements Log {
    public final static  String server_name= "HTTP RIT2 2020/2021 by Pedro Capelo 52511";
    public final static String HOMEFILENAME= "index.htm";
    static public SSLContext sslContext= null;
    final static int DefaultMaxThreads= 10; // Maximum number of threads
    final static int MaxAcceptLog= 10;  // Accepts up to 10 pending TCP connections
    SHttpd main_thread= null; //http thread 
    SHttpd main_sthread = null; //https thread
    public ServerSocket server; // normal TCP server socket
    public javax.net.ssl.SSLServerSocket serverS; // Secure TCP server
    
    public int max_threads= DefaultMaxThreads;
    public int n_threads= 0;
    final Integer lock= new Integer(0);
    
    /** Creates new form guiHttpd */
    public guiHttpd () {
        initComponents ();
        try {
            initContext();
        } catch (Exception e) {
            System.out.println("Error loading security context");
        }
        setTitle(server_name);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jTextPorto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextSPorto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextIP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextRaizHtml = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextPasswd = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextKeepAlive = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextThreads = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextMaxThreads = new javax.swing.JTextField();
        jCheckCookieAuth = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("HTTP RIT2 2015/2016 by ?????/?????/?????");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(520, 126));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 35));
        jPanel1.setName("Estado"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 35));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jToggleButton1.setText("Active");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(85, 29));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(85, 29));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Port");
        jLabel4.setMaximumSize(new java.awt.Dimension(35, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(35, 17));
        jPanel1.add(jLabel4);

        jTextPorto.setText("20000");
        jPanel1.add(jTextPorto);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Port");
        jLabel7.setMaximumSize(new java.awt.Dimension(35, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(35, 17));
        jPanel1.add(jLabel7);

        jTextSPorto.setText("20043");
        jTextSPorto.setToolTipText("");
        jTextSPorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSPortoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextSPorto);

        jLabel5.setText("IP");
        jPanel1.add(jLabel5);

        jTextIP.setEditable(false);
        jTextIP.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel1.add(jTextIP);

        getContentPane().add(jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(520, 37));
        jPanel3.setMinimumSize(new java.awt.Dimension(60, 33));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 33));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("Html:");
        jPanel3.add(jLabel8);

        jTextRaizHtml.setText("/home/user/Desktop/rit2_t1_students/html");
        jTextRaizHtml.setToolTipText("");
        jTextRaizHtml.setPreferredSize(new java.awt.Dimension(340, 20));
        jTextRaizHtml.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextRaizHtmlFocusLost(evt);
            }
        });
        jTextRaizHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRaizHtmlActionPerformed(evt);
            }
        });
        jPanel3.add(jTextRaizHtml);

        jLabel9.setText(" Password ");
        jPanel3.add(jLabel9);

        jTextPasswd.setText("user:pass");
        jPanel3.add(jTextPasswd);

        getContentPane().add(jPanel3);

        jPanel2.setToolTipText("configuração");
        jPanel2.setMaximumSize(new java.awt.Dimension(620, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel2.setName("configuracao"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 35));

        jButtonClear.setText("Clear");
        jButtonClear.setMaximumSize(new java.awt.Dimension(75, 29));
        jButtonClear.setPreferredSize(new java.awt.Dimension(75, 29));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClear);

        jLabel1.setText("  Keep-Alive: ");
        jPanel2.add(jLabel1);

        jTextKeepAlive.setText("3000");
        jTextKeepAlive.setPreferredSize(new java.awt.Dimension(30, 19));
        jTextKeepAlive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKeepAliveActionPerformed(evt);
            }
        });
        jPanel2.add(jTextKeepAlive);

        jLabel3.setText(" Threads: ");
        jPanel2.add(jLabel3);

        jTextThreads.setEditable(false);
        jTextThreads.setText("0");
        jTextThreads.setPreferredSize(new java.awt.Dimension(30, 19));
        jPanel2.add(jTextThreads);

        jLabel6.setText("  Max: ");
        jPanel2.add(jLabel6);

        jTextMaxThreads.setText("10");
        jTextMaxThreads.setPreferredSize(new java.awt.Dimension(30, 19));
        jPanel2.add(jTextMaxThreads);

        jCheckCookieAuth.setText(" cookie passwd");
        jCheckCookieAuth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel2.add(jCheckCookieAuth);

        getContentPane().add(jPanel2);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(360, 180));

        jTextArea1.setLineWrap(true);
        jTextArea1.setPreferredSize(new java.awt.Dimension(200, 2000));
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        getAccessibleContext().setAccessibleName("HTTP GUI - RIT2 2011/2012 by ?????/?????/?????");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Validates the html root directory name (only for Linux) */
    public void validate_name (javax.swing.JTextField f) {
        String str= f.getText ();
        if (str.length () == 0)
            return;
        
        char separator;
        if (str.indexOf ("\\") != -1)
            // Running in Windows
            separator= '\\';
        else
            // Running in Linux
            separator= '/';
        
        if (str.charAt (str.length ()-1) != separator) {
            str= str + separator;
        } else {
            while ((str.length ()>1) && (str.charAt (str.length ()-2) == separator)) {
                str= str.substring (0, str.length ()-1);
            }
        }
        f.setText (str);
    }
    
    /** Automatically validates the html directory name */
    private void jTextRaizHtmlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRaizHtmlFocusLost
        validate_name (jTextRaizHtml);
    }//GEN-LAST:event_jTextRaizHtmlFocusLost
        
    /** Cleans the text area */
    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText ("");
    }//GEN-LAST:event_jButtonClearActionPerformed
    
    /** Cleans the text area */
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        if (evt.getKeyChar () == ' ')
            jTextArea1.setText ("");
    }//GEN-LAST:event_jTextArea1KeyPressed
    
    /** Starts and stops the web server */
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected ()) {
            // Parse UI parameters            
            int porto;   // HTTP port
            try {
                porto= Integer.parseInt (jTextPorto.getText ());
            } catch (NumberFormatException e) {
                Log ("Invalid port number\n");
                jToggleButton1.setSelected (false);
                return;
            }
            int portoS; // HTTPS port
            try {
                portoS= Integer.parseInt(jTextSPorto.getText());
            } catch (NumberFormatException e) {
                Log("Invalid https port number\n");
                jToggleButton1.setSelected(false);
                return;
            }
            // Starts http web server
            try {
                server= new ServerSocket (porto, MaxAcceptLog);
            } catch (java.io.IOException e) {
                Log ("Server start failure: " + e + "\n");
                jToggleButton1.setSelected (false);
                return;
            }
             // Starts https server
            try {
                SSLServerSocketFactory sslSrvFact = sslContext.getServerSocketFactory();
                serverS =(SSLServerSocket)sslSrvFact.createServerSocket(portoS);
                serverS.setNeedClientAuth(false);
            } catch (java.io.IOException e) {
                Log("Server start failure: " + e + "\n");
                jToggleButton1.setSelected(false);
                return;
            }
            // Gets local IP
            try {
                jTextIP.setText (InetAddress.getLocalHost ().getHostAddress ());
            } catch (UnknownHostException e) {
                Log ("Failed to get local IP: "+e+"\n");
            }
            // starts main thread
            main_thread= new SHttpd ( this, server, false);
            main_sthread= new SHttpd( this, serverS, true);
            n_threads= 0;
            jTextThreads.setText ("0");
            max_threads= getMaxThreads ();
            main_thread.start ();
            main_sthread.start ();
            
            setEditable_jText (false);
        } else {
            // Stops web server
            try {
                 if (main_thread != null) {
                    main_thread.stop_thread ();
                    main_thread= null;
                }
                if (main_sthread != null) {
                    main_sthread.stop_thread();
                    main_sthread= null;
                }
                if (server != null) {
                    server.close ();
                    server= null;
                }
                if (serverS != null) {
                    serverS.close();
                    serverS = null;
                }
            } catch (IOException e) {
                Log ("Exception closing server socket: "+e+"\n");
            }
            jTextIP.setText ("");
            setEditable_jText (true);
            n_threads= 0;
            jTextThreads.setText ("0");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit (0);
    }//GEN-LAST:event_exitForm

    private void jTextRaizHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRaizHtmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRaizHtmlActionPerformed

    private void jTextKeepAliveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKeepAliveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKeepAliveActionPerformed

    private void jTextSPortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSPortoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSPortoActionPerformed
    
    /** Controls editability of jTexts */
    public void setEditable_jText (boolean editable) {
        jTextPorto.setEditable (editable);
        jTextRaizHtml.setEditable (editable);
        jTextMaxThreads.setEditable (editable);
    }
    
    /** Logs a message on the command line and on the text area */
    @Override
    public void Log (String s) {
        synchronized (lock) {
            jTextArea1.append (s);
            System.out.print (s);
        }
    }
    /** Returns the HTTP port number */
    public String getIp () {
        try {
            return  jTextIP.getText();
        } catch (NumberFormatException e) {
            return null;
        }
    }
   /** Returns the HTTP port number */
    public int getPortHTTP () {
        try {
            return Integer.parseInt (jTextPorto.getText ());
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    /** Returns the HTTPS port number */
    public int getPortHTTPS() {
        try {
            return Integer.parseInt(jTextSPorto.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    /** Returns if it must redirect HTTP to HTTPS links and use cookie passwd*/
    public boolean redirectToHTTPS() {
        return jCheckCookieAuth.isSelected();
    }
    
    /** Returns the page password - if empty then no authentication is used */
    public String user_passwd() {
        return jTextPasswd.getText();
    }

    public boolean cookie_passwd() {
        return jCheckCookieAuth.isSelected();
    }
    
    /** Returns the keep alive interval value */
    public int getKeepAlive () {
        String txt= jTextKeepAlive.getText ();
        if (txt == null)
            return 0;
        try {
            return 1000*Integer.parseInt (txt);
        } catch (NumberFormatException e) {
            Log ("Invalid KeepAlive value: '"+txt+"'\n");
            return 0;
        }
    }
    
    /** Local function - use 'max_threads' variable */
    private int getMaxThreads () {
        String txt= jTextMaxThreads.getText ();
        if (txt == null)
            return 0;
        try {
            return 1000*Integer.parseInt (txt);
        } catch (NumberFormatException e) {
            Log ("Invalid MaxThreads value: '"+txt+"' - using "+
                    DefaultMaxThreads+"\n");
            return DefaultMaxThreads;
        }
    }
    
    /** Returns the root html directory */
    public String getRaizHtml () {
        return jTextRaizHtml.getText ();
    }
    
    /** Callback called when a new HTTP connection thread starts */
    public void thread_started () {
        if (main_thread != null) {
            n_threads++;
            jTextThreads.setText (Integer.toString (n_threads));
        }
    }
    
    /** Callback called when a HTTP connection thread ends */
    public void thread_ended () {
        if (main_thread != null) {
            n_threads--;
            jTextThreads.setText (Integer.toString (n_threads));

            // ???
        }
    }
    
    /** Returns the number of active connections */
    public int active_connects () {
        if (main_thread == null)
            return 0;
        return n_threads;
    }

    /** Returns true if main_thread is active */
    public boolean active () {
        return (main_thread != null);
    }
 /** Open up the KeyStore to obtain the Trusted Certificates.
     *  KeyStore is of type "JKS". Filename is "serverAppKeys.jks"
     *  and password is "myKeys".
     */
    private static void initContext() throws Exception {
        if (sslContext != null)
            return;
        
        try {
            // MAke sure that JSSE is available
            Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            
            // Create/initialize the SSLContext with key material
            char[] passphrase = "password".toCharArray(); // if the certificate was created with the password = "password"
            
            KeyStore ksKeys;
            try {
                // First initialize the key and trust material.
                ksKeys= KeyStore.getInstance("JKS");
            } catch (Exception e) {
                System.out.println("KeyStore.getInstance: "+e);
                return;
            }
            ksKeys.load(new FileInputStream("keystore"), passphrase);
            System.out.println("KsKeys has "+ksKeys.size()+" keys after load");
            
//            KeyStore ksTrust = KeyStore.getInstance("JKS");
//            ksTrust.load(new FileInputStream("truststore"), passphrase);
            
            // KeyManager's decide which key material to use.
            KeyManagerFactory kmf =
                    KeyManagerFactory.getInstance("SunX509");
            kmf.init(ksKeys, passphrase);
            System.out.println("KMfactory default alg.: "+KeyManagerFactory.getDefaultAlgorithm());
            
            // TrustManager's decide whether to allow connections.
//            TrustManagerFactory tmf =
//                TrustManagerFactory.getInstance("SunX509");
//            tmf.init(ksTrust);
//            System.out.println("TMfactory default alg.: "+tmf.getDefaultAlgorithm());
            
            sslContext = SSLContext.getInstance("TLSv1.2"); 
            sslContext.init(
                    kmf.getKeyManagers(), null /*tmf.getTrustManagers()*/, null);
            
        } catch (Exception e) {
            System.out.println("Failed to read keystore and trustfile.");
            e.printStackTrace();
            throw e;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        new guiHttpd ().setVisible(true);
    }
    
  
    
    /** Handles client connections */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JCheckBox jCheckCookieAuth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextIP;
    private javax.swing.JTextField jTextKeepAlive;
    private javax.swing.JTextField jTextMaxThreads;
    private javax.swing.JTextField jTextPasswd;
    private javax.swing.JTextField jTextPorto;
    private javax.swing.JTextField jTextRaizHtml;
    private javax.swing.JTextField jTextSPorto;
    private javax.swing.JTextField jTextThreads;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}


